### ISSUE TITLE
Precision of Mpfr and &Mpfr operations

### ISSUE THREAD

**Issue by Moredread** [fizyk20/rust-mpfr#12]
The precision of operations (Add, Sub, Mul, Div) that work on Mpfr and take a &Mpfr don't have the same convention regarding precision as the other operations (i.e. choosing the highest precision of the inputs for the output).

This actually was a problem in my code as I was wondering why high precision calculations had low precision results, when mixing cloned values and references (i.e. with constants).

I think the same convention should apply for those too, even if in place mutation isn't possible anymore. At least there should be a huge warning in the docs/comments that mixing Mpfr and &Mpfr has different results than the rest. (I guess benching if in place mutation is even worth it would also be helpful.)

I've have a few more tests regarding this (and other stuff), and a "fixed" implementation in the [Moredread:wip](https://github.com/Moredread/rust-mpfr/tree/wip) branch. But I'm not sure if both implementations for &Mpfr/&Mpfr and &Mpfr/Mpfr might be merged.

Also some of the tests might be superfluous, I don't know the exact rules for commutation of the types.

What is your opinion on this? (Esp. is it clear what I mean? It's a bit late here as I'm writing this XD)

**Comment by Moredread** [comment]
To answer the performance question partially, my Mandelbrot code takes 75ms with in place calculation and 100ms without... So there is definitively something worth investigating there.

Still, consistency is more important than performance imho.

**Comment by fizyk20** [comment]
Hmm, I see the problem. But unfortunately your fix would revert the changes allowing for in-place mutation, which was quite a big performance gain (what you already noticed from what I see).

IIRC it is possible to change the precision of an already existing Mpfr object, though, so that might be the way to go (if the &Mpfr argument has higher precision, update the precision of `self` and only then perform the operation). I'll have to investigate when I get back home.
